/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
import data.StudentDataManager;
import model.ProgrammingPlatform;
import model.Student;
import service.AnalysisService;
import service.StudentService;
import exception.InvalidInputException;
/**
 *
 * @author BANU
 */
public class StudentFrame extends javax.swing.JFrame {
    
    private List<JTextField> platformNameFields = new ArrayList<>();
private List<JTextField> platformRankFields = new ArrayList<>();
private List<JTextField> platformScoreFields = new ArrayList<>();
private List<JTextField> platformProblemsFields = new ArrayList<>();

private final StudentDataManager dataManager;
private final AnalysisService analysisService;
private final StudentService studentService;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentFrame.class.getName());
private void generatePlatformFields() {

    // Clear old platform fields
    pnlPlatforms.removeAll();

    platformNameFields.clear();
    platformRankFields.clear();
    platformScoreFields.clear();
    platformProblemsFields.clear();

    // Get number of platforms
    int numberOfPlatforms;

    try {
        numberOfPlatforms =
                Integer.parseInt(txtPlatformCount.getText().trim());

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter a valid number of platforms.",
                "Invalid Input",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    // Validate number of platforms
    if (numberOfPlatforms <= 0) {

        JOptionPane.showMessageDialog(
                this,
                "Number of platforms must be greater than 0.",
                "Invalid Input",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    // Layout for multiple platforms
    pnlPlatforms.setLayout(
            new GridLayout(numberOfPlatforms, 1, 5, 5)
    );

    // Create fields for each platform
    for (int i = 0; i < numberOfPlatforms; i++) {

        JPanel platformPanel = new JPanel();

        // Two rows and four columns
        platformPanel.setLayout(
        new java.awt.FlowLayout(
                java.awt.FlowLayout.LEFT,
                5,
                5
        )
);

        JTextField nameField = new JTextField(8);
        JTextField rankField = new JTextField(8);
        JTextField scoreField = new JTextField(8);
        JTextField problemsField = new JTextField(8);

        // Row 1
        platformPanel.add(
                new JLabel("Platform " + (i + 1) + " Name:")
        );

        platformPanel.add(nameField);

        platformPanel.add(
                new JLabel("Rank:")
        );

        platformPanel.add(rankField);

        // Row 2
        platformPanel.add(
                new JLabel("Score:")
        );

        platformPanel.add(scoreField);

        platformPanel.add(
                new JLabel("Problems Solved:")
        );

        platformPanel.add(problemsField);

        // Add platform panel
        pnlPlatforms.add(platformPanel);

        // Store fields
        platformNameFields.add(nameField);
        platformRankFields.add(rankField);
        platformScoreFields.add(scoreField);
        platformProblemsFields.add(problemsField);
    }

    // Refresh panel
    pnlPlatforms.revalidate();
    pnlPlatforms.repaint();
}
    public StudentFrame() {
    initComponents();

    dataManager = new StudentDataManager();
    analysisService = new AnalysisService();
    studentService = new StudentService(
            dataManager,
            analysisService
    );

    setSize(700, 520);
    setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegisterNumber = new javax.swing.JLabel();
        txtRegisterNumber = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        lblCgpa = new javax.swing.JLabel();
        txtCgpa = new javax.swing.JTextField();
        lblAptitudeRank = new javax.swing.JLabel();
        txtAptitudeRank = new javax.swing.JTextField();
        lblPlatformCount = new javax.swing.JLabel();
        txtPlatformCount = new javax.swing.JTextField();
        btnGeneratePlatforms = new javax.swing.JButton();
        pnlPlatforms = new javax.swing.JPanel();
        btnAddStudent = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Student");

        lblRegisterNumber.setText("Register Number:");

        lblName.setText("Name:");

        lblDepartment.setText("Department:");

        lblYear.setText("Year:");

        lblCgpa.setText("CGPA:");

        lblAptitudeRank.setText("Aptitude Rank:");

        lblPlatformCount.setText("Number of Platforms:");

        btnGeneratePlatforms.setText("Generate Platforms");
        btnGeneratePlatforms.addActionListener(this::btnGeneratePlatformsActionPerformed);

        javax.swing.GroupLayout pnlPlatformsLayout = new javax.swing.GroupLayout(pnlPlatforms);
        pnlPlatforms.setLayout(pnlPlatformsLayout);
        pnlPlatformsLayout.setHorizontalGroup(
            pnlPlatformsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPlatformsLayout.setVerticalGroup(
            pnlPlatformsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(this::btnAddStudentActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPlatforms, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblAptitudeRank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblRegisterNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCgpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblPlatformCount))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPlatformCount, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtRegisterNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addComponent(txtName)
                                        .addComponent(txtDepartment)
                                        .addComponent(txtYear)
                                        .addComponent(txtCgpa)
                                        .addComponent(txtAptitudeRank))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(btnGeneratePlatforms)))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnAddStudent)
                .addGap(73, 73, 73)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegisterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegisterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCgpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAptitudeRank)
                    .addComponent(txtAptitudeRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlatformCount)
                    .addComponent(txtPlatformCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGeneratePlatforms)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPlatforms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStudent)
                    .addComponent(btnClear))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneratePlatformsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePlatformsActionPerformed
        // TODO add your handling code here:
        generatePlatformFields();
    }//GEN-LAST:event_btnGeneratePlatformsActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        addStudentFromForm();
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtRegisterNumber.setText("");
    txtName.setText("");
    txtDepartment.setText("");
    txtYear.setText("");
    txtCgpa.setText("");
    txtAptitudeRank.setText("");

    // Reset platform count
    txtPlatformCount.setText("");

    // Clear dynamically generated platform fields
    pnlPlatforms.removeAll();

    platformNameFields.clear();
    platformRankFields.clear();
    platformScoreFields.clear();
    platformProblemsFields.clear();

    // Refresh the platform panel
    pnlPlatforms.revalidate();
    pnlPlatforms.repaint();

    // Put cursor back in Register Number field
    txtRegisterNumber.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed
    
    private void addStudentFromForm() {

    try {

        // Read basic student information
        String registerNumber =
                txtRegisterNumber.getText().trim();

        String name =
                txtName.getText().trim();

        String department =
                txtDepartment.getText().trim();

        int year =
                Integer.parseInt(txtYear.getText().trim());

        double cgpa =
                Double.parseDouble(txtCgpa.getText().trim());

        int aptitudeRank =
                Integer.parseInt(txtAptitudeRank.getText().trim());

        // Create Student object
        Student student = new Student(
                registerNumber,
                name,
                department,
                year,
                cgpa,
                aptitudeRank
        );

        // Add programming platforms
        for (int i = 0; i < platformNameFields.size(); i++) {

            String platformName =
                    platformNameFields.get(i).getText().trim();

            int rank =
                    Integer.parseInt(
                            platformRankFields.get(i)
                                    .getText().trim()
                    );

            double score =
                    Double.parseDouble(
                            platformScoreFields.get(i)
                                    .getText().trim()
                    );

            int problemsSolved =
                    Integer.parseInt(
                            platformProblemsFields.get(i)
                                    .getText().trim()
                    );

            ProgrammingPlatform platform =
                    new ProgrammingPlatform(
                            platformName,
                            rank,
                            score,
                            problemsSolved
                    );

            student.getPlatforms().add(platform);
        }

        // Send student to backend
        studentService.addStudent(student);

        JOptionPane.showMessageDialog(
                this,
                "Student added successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter valid numeric values.",
                "Invalid Input",
                JOptionPane.ERROR_MESSAGE
        );

    } catch (InvalidInputException e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Invalid Input",
                JOptionPane.ERROR_MESSAGE
        );
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGeneratePlatforms;
    private javax.swing.JLabel lblAptitudeRank;
    private javax.swing.JLabel lblCgpa;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPlatformCount;
    private javax.swing.JLabel lblRegisterNumber;
    private javax.swing.JLabel lblYear;
    private javax.swing.JPanel pnlPlatforms;
    private javax.swing.JTextField txtAptitudeRank;
    private javax.swing.JTextField txtCgpa;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPlatformCount;
    private javax.swing.JTextField txtRegisterNumber;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
