/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import data.StudentDataManager;
import model.Student;
import service.AnalysisService;
import service.StudentService;

import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author BANU
 */
public class ViewStudentsFrame extends javax.swing.JFrame {
    
    private StudentDataManager dataManager;
private AnalysisService analysisService;
private StudentService studentService;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewStudentsFrame.class.getName());

    /**
     * Creates new form ViewStudentsFrame
     */
    public ViewStudentsFrame() {
    initComponents();
    tblStudents.setDefaultEditor(Object.class, null);
    dataManager = new StudentDataManager();
    analysisService = new AnalysisService();
    studentService = new StudentService(
            dataManager,
            analysisService
    );

    setSize(800, 500);
    setLocationRelativeTo(null);
    
    loadStudents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        btnViewAnalysis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("   Student Records");

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Register Number", "Name", "Department", "Year", "CGPA", "Programming Score", "Placement Readiness"
            }
        ));
        jScrollPane1.setViewportView(tblStudents);

        btnClose.setText("Close");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        btnViewAnalysis.setText("View Analysis");
        btnViewAnalysis.addActionListener(this::btnViewAnalysisActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnViewAnalysis)
                .addGap(74, 74, 74)
                .addComponent(btnClose)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAnalysis)
                    .addComponent(btnClose))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnViewAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAnalysisActionPerformed
    int selectedRow = tblStudents.getSelectedRow();

    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please select a student first.",
                "No Student Selected",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    String regNo = tblStudents
            .getValueAt(selectedRow, 0)
            .toString();

    Student selectedStudent = studentService
            .getAllStudents()
            .stream()
            .filter(s -> s.getRegisterNumber().equalsIgnoreCase(regNo))
            .findFirst()
            .orElse(null);

    if (selectedStudent == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Student details could not be found.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    StudentAnalysisFrame analysisFrame =
            new StudentAnalysisFrame(selectedStudent);

    analysisFrame.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAnalysisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewStudentsFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnViewAnalysis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblStudents;
    // End of variables declaration//GEN-END:variables
private void loadStudents() {

    List<Student> students = studentService.getAllStudents();

    DefaultTableModel model =
            (DefaultTableModel) tblStudents.getModel();

    model.setRowCount(0);

    for (Student student : students) {

        model.addRow(new Object[]{
            student.getRegisterNumber(),
            student.getName(),
            student.getDepartment(),
            student.getYear(),
            student.getCgpa(),
            student.getProgrammingScore(),
            student.getPlacementReadiness()
        });
    }
}
}
